// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEo6l-MgeI0tJyIpIZZgfzgDSL5l6z1p0',
    appId: '1:662961634092:web:5cb4b95b21c264fc0dca89',
    messagingSenderId: '662961634092',
    projectId: 'ristorderproject',
    authDomain: 'ristorderproject.firebaseapp.com',
    storageBucket: 'ristorderproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2IUKrnbDOTiJ3qtVSdK786LhgovLjhE',
    appId: '1:662961634092:android:6cd5bc4dad4f2c2b0dca89',
    messagingSenderId: '662961634092',
    projectId: 'ristorderproject',
    storageBucket: 'ristorderproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS6EV9C0LBGux_q_ZIqOHoml2d76Fnk3o',
    appId: '1:662961634092:ios:3eb4f138ec04727d0dca89',
    messagingSenderId: '662961634092',
    projectId: 'ristorderproject',
    storageBucket: 'ristorderproject.appspot.com',
    iosBundleId: 'com.example.ristorderproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS6EV9C0LBGux_q_ZIqOHoml2d76Fnk3o',
    appId: '1:662961634092:ios:3eb4f138ec04727d0dca89',
    messagingSenderId: '662961634092',
    projectId: 'ristorderproject',
    storageBucket: 'ristorderproject.appspot.com',
    iosBundleId: 'com.example.ristorderproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEo6l-MgeI0tJyIpIZZgfzgDSL5l6z1p0',
    appId: '1:662961634092:web:d7acd9b0b8c6754f0dca89',
    messagingSenderId: '662961634092',
    projectId: 'ristorderproject',
    authDomain: 'ristorderproject.firebaseapp.com',
    storageBucket: 'ristorderproject.appspot.com',
  );
}
